apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/jayanth-tjvrr/ar-test-int//arlonctl?ref=main
configurations:
- configurations.yaml
patchesStrategicMerge:
- patch.yaml
